FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

CONFIG_DTFILE_USER_DTSI ?= "renode.dtsi"

EXTRA_DT_INCLUDE_FILES:append = "${CONFIG_DTFILE_USER_DTSI}"
EXTRA_DT_FILES:append = "${CONFIG_DTFILE_USER_DTSI}"
