image: debian:bookworm

stages:
  - build
  - local-tests

.common:
  only:
    refs:
      - master
      - merge_requests

.build:
  extends: .common
  stage: build
  variables:
    ENABLE_TRANSFORMERS: "--enable-transformers"
  before_script:
    - apt update
    - apt -qqy install --no-install-recommends gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool file locales libacl1 pipx curl openssh-client sudo gfortran &>/dev/null
    - git config --global url."$CI_URL".insteadOf https://github.com/antmicro/
    - curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo && chmod a+rx /usr/bin/repo
    - PIPX_BIN_DIR=/usr/bin/ pipx install git+https://github.com/antmicro/tuttest@63160-snippet-transform
    - sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && locale-gen
    - export LANG=en_US.UTF-8
    - ln -sf /usr/share/zoneinfo/UTC0 /usr/share/zoneinfo/UTC
    - useradd -m builder

.rdfm-unmatched-demo:
  extends: .build
  script:
    - cd demos/rdfm-unmatched-demo
    - tuttest README.md fetch-sources $ENABLE_TRANSFORMERS | bash -
    - chown -R builder:root .
    - cd rdfm-unmatched-demo
    - tuttest ../README.md setup-yocto,target-renode,build-image | sudo -u builder XZ_MEMLIMIT=25% XZ_DEFAULTS=--memlimit-compress=25% BB_ENV_PASSTHROUGH_ADDITIONS="XZ_MEMLIMIT XZ_DEFAULTS" bash -eo pipefail -
    - cd ..
    - tuttest README.md copy-artifacts | bash -eo pipefail -
  artifacts:
    expire_in: 4 hours
    paths:
      - demos/rdfm-unmatched-demo/renode/rdfm-image-minimal-unmatched.rdfm
      - demos/rdfm-unmatched-demo/renode/rdfm-image-upgraded-unmatched.rdfm
      - demos/rdfm-unmatched-demo/renode/u-boot-spl.bin
      - demos/rdfm-unmatched-demo/renode/u-boot.itb
      - demos/rdfm-unmatched-demo/renode/sdcard.sdimg

# meta-antmicro = HEAD (for info purposes only - manifest is to be considered the ground truth for building demos)
RDFM Unmatched Demo (HEAD):
  extends: .rdfm-unmatched-demo
  allow_failure: true

# meta-antmicro = manifest revision
RDFM Unmatched Demo (Upstream):
  extends: .rdfm-unmatched-demo
  variables:
    ENABLE_TRANSFORMERS: ""

.jetson-orin-baseboard-demo:
  extends: .build
  script:
    - cd demos/nvidia-jetson-orin-baseboard-demo
    - tuttest README.md fetch-repo $ENABLE_TRANSFORMERS | bash -
    - chown -R builder:root .
    - cd orin-baseboard-demo
    - tuttest ../README.md build-bsp | sudo -u builder XZ_MEMLIMIT=25% XZ_DEFAULTS=--memlimit-compress=25% BB_ENV_PASSTHROUGH_ADDITIONS="XZ_MEMLIMIT XZ_DEFAULTS" bash -eo pipefail -
  artifacts:
    paths:
      - demos/nvidia-jetson-orin-baseboard-demo/orin-baseboard-demo/build/tmp/deploy/images/p3509-a02-p3767-0000

# meta-antmicro = HEAD (for info purposes only - manifest is to be considered the ground truth for building demos)
Jetson Orin Baseboard Demo (HEAD):
  extends: .jetson-orin-baseboard-demo
  allow_failure: true

# meta-antmicro = manifest revision
Jetson Orin Baseboard Demo (Upstream):
  extends: .jetson-orin-baseboard-demo
  variables:
    ENABLE_TRANSFORMERS: ""

build-rdfm-artifact:
  extends: .common
  stage: build
  before_script:
    - apt update
    - apt -qqy install --no-install-recommends golang gcc make ca-certificates pkg-config git libc-dev liblzma-dev libssl-dev
  script:
    - git clone https://github.com/antmicro/rdfm.git
    - make -C rdfm/tools/rdfm-artifact install GOBIN=$(pwd)
  artifacts:
    expire_in: 1 day
    paths:
      - rdfm-artifact

test-rdfm-unmatched-demo:
  extends: .common
  stage: local-tests
  dependencies: [ 'RDFM Unmatched Demo (Upstream)', 'build-rdfm-artifact' ]
  before_script:
    - apt update
    - apt install -qqy iproute2 python3-venv python-is-python3 git wget sudo dirmngr ca-certificates gnupg &>/dev/null
    - gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    - echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/debian stable-buster main" > /etc/apt/sources.list.d/mono-official-stable.list
    - wget --progress=dot:mega 'https://builds.renode.io/renode_1.15.0+20240319git9111b18ef_amd64.deb' -O renode.deb
    - apt update && apt -qqy install mono-complete ./renode.deb
    - python -m venv demo && source demo/bin/activate
    - pip install 'pyrenode3[all] @ git+https://github.com/antmicro/pyrenode3.git' 'tuttest @ git+https://github.com/antmicro/tuttest.git'
  script:
    - export PATH="${PATH}:$(pwd)"
    - source demo/bin/activate
    - cd demos/rdfm-unmatched-demo/renode
    - tuttest ../README.md create-delta,setup-tap,setup-host | bash -eo pipefail -
    - (tuttest ../README.md start-server | bash -eo pipefail -) &
    - (tail -F uart0.log 2>/dev/null) &
    - python unmatched.py
  artifacts:
    when: always
    paths:
      - demos/rdfm-unmatched-demo/renode/uart0.log
