#!/bin/bash

if [ -n "$BASH_SOURCE"  ]; then
        this_script=$BASH_SOURCE
    elif [ -n "$ZSH_NAME"  ]; then
            this_script=$0
        else
                this_script="$(pwd)/setup-environment"
fi

script_dir=$(dirname "$this_script")
script_dir=$(readlink -f "$script_dir")
build_dir=${script_dir}/build

rm ${script_dir}/sources/meta-sifive/recipes-connectivity/bind/bind_9.16.5.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-core/glibc/cross-localedef-native_2.32.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-core/kbd/kbd_2.3.0.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-devtools/clang/clang_git.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-devtools/clang/llvm-project-source.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-devtools/qemu/qemu-native_5.1.0.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-devtools/qemu/qemu-system-native_5.1.0.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-devtools/qemu/qemu_5.1.0.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-extended/man-pages/man-pages_5.08.bbappend
rm ${script_dir}/sources/meta-sifive/recipes-graphics -rf

. ${script_dir}/sources/poky/oe-init-build-env ${build_dir}
