#! /bin/sh

### BEGIN INIT INFO
# Provides: darknet-demo
# Required-Start: xserver
# Should-Start: maxpower
### END INIT INFO

DATA_DIR=/usr/share/darknet-demo

case "$1" in
    start)
        DISPLAY=:0 /usr/bin/darknet-demo -i 0 -n ${DATA_DIR}/coco.names -c ${DATA_DIR}/yolov4.cfg -w ${DATA_DIR}/yolov4.weights -f > ${DATA_DIR}/initlog 2>&1 
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 (start|stop)"
        ;;
esac
